server:
  port: 8086

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/notificationsdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
    template:
      default-receive-queue: notification-queue
