server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/products/**

        - id: inventory-service
          uri: http://inventory-service:8082
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/orders/**

        - id: user-service
          uri: http://user-service:8084
          predicates:
            - Path=/users/**

        - id: cart-service
          uri: http://cart-service:8085
          predicates:
            - Path=/cart/**

        - id: auth-service
          uri: http://auth-service:8086
          predicates:
            - Path=/auth/**

jwt:
  secret: secret_key_for_jwt
