
  spring:
    data:
      mongodb:
        uri: mongodb://localhost:27017/ecommerce
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  server:
    port: 8083


