server:
  port: 8084

spring:
  application:
    name: cart-service

  data:
    mongodb:
      uri: mongodb://mongo:27017/cartdb

  cache:
    type: redis

  redis:
    host: redis
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.cart_service: DEBUG
